import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
    screen: { flex: 1, backgroundColor: '#F3F6FC' },
    content: { minHeight: '100%', alignItems: 'center', paddingHorizontal: 24, overflow: 'hidden' },
    ambientTop: {
        position: 'absolute',
        top: 112,
        left: 78,
        width: 230,
        height: 230,
        borderRadius: 115,
        backgroundColor: '#DCEBFF88',
    },
    ambientBottom: {
        position: 'absolute',
        right: -38,
        bottom: 70,
        width: 210,
        height: 210,
        borderRadius: 105,
        backgroundColor: '#DDF7E599',
    },
    brandMark: {
        width: 66,
        height: 66,
        marginTop: 4,
        alignItems: 'center',
        justifyContent: 'center',
        borderRadius: 21,
        shadowColor: '#0A84FF',
        shadowOffset: { width: 0, height: 9 },
        shadowOpacity: 0.25,
        shadowRadius: 16,
        elevation: 6,
    },
    brandBadge: {
        position: 'absolute',
        top: -6,
        right: -7,
        width: 25,
        height: 25,
        borderRadius: 13,
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: '#34C759',
        borderWidth: 2,
        borderColor: '#F3F6FC',
    },
    brandName: { marginTop: 11, color: '#1C1C1E', fontSize: 21, fontWeight: '800' },
    brandCaption: { marginTop: 3, color: '#6E6E73', fontSize: 12 },
    previewCard: {
        width: '100%',
        marginTop: 22,
        padding: 17,
        borderRadius: 24,
        backgroundColor: '#FFFFFFD9',
        borderWidth: 1,
        borderColor: '#FFFFFFCC',
        shadowColor: '#2D4C7A1F',
        shadowOffset: { width: 0, height: 12 },
        shadowOpacity: 0.55,
        shadowRadius: 18,
        elevation: 4,
    },
    previewHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
    previewLabel: { color: '#6E6E73', fontSize: 11, fontWeight: '600' },
    previewTotal: { marginTop: 5, color: '#1C1C1E', fontSize: 23, fontWeight: '800' },
    growthChip: {
        flexDirection: 'row', alignItems: 'center', gap: 4,
        paddingHorizontal: 10, paddingVertical: 7, borderRadius: 14, backgroundColor: '#34C759',
    },
    growthValue: { color: '#FFFFFF', fontSize: 12, fontWeight: '700' },
    previewSubtext: { marginTop: 13, color: '#8E8E93', fontSize: 11 },
    chartArea: { height: 102, flexDirection: 'row', alignItems: 'flex-end', gap: 12, paddingHorizontal: 8, paddingTop: 9 },
    barSlot: { flex: 1, height: '100%', justifyContent: 'flex-end', alignItems: 'center' },
    bar: { width: 17, borderTopLeftRadius: 7, borderTopRightRadius: 7 },
    previewFooter: { marginTop: 9, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
    previewPeriod: { color: '#8E8E93', fontSize: 10 },
    trendCaption: { flexDirection: 'row', alignItems: 'center', gap: 4 },
    trendCaptionText: { color: '#34C759', fontSize: 11, fontWeight: '700' },
    headline: { marginTop: 22, color: '#1C1C1E', fontSize: 21, fontWeight: '800' },
    description: { marginTop: 7, color: '#6E6E73', fontSize: 12, lineHeight: 19, textAlign: 'center' },
    featureRow: { width: '100%', flexDirection: 'row', justifyContent: 'space-between', marginTop: 15 },
    featureItem: {
        flex: 1, minHeight: 32, flexDirection: 'row', alignItems: 'center', justifyContent: 'center',
        gap: 5, paddingHorizontal: 4, borderRadius: 12, backgroundColor: '#FFFFFFA8',
    },
    featureLabel: { color: '#6E6E73', fontSize: 9, fontWeight: '600' },
    loadingArea: { alignItems: 'center', marginTop: 22, marginBottom: 12 },
    loadingText: { marginTop: 7, color: '#8E8E93', fontSize: 11 },
    progressTrack: { width: 160, height: 4, overflow: 'hidden', borderRadius: 2, marginTop: 8, backgroundColor: '#DCEBFF' },
    progressFill: { width: '52%', height: '100%', borderRadius: 2 },
});
