import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
    container: { flex: 1 },
    scrollContent: { padding: 16, paddingBottom: 112 },
    stickyOverlay: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        zIndex: 20,
    },
    stickyHeader: {
        borderBottomWidth: 1,
        borderBottomLeftRadius: 22,
        borderBottomRightRadius: 22,
        shadowOffset: { width: 0, height: 8 },
        shadowOpacity: 0.14,
        shadowRadius: 18,
        elevation: 12,
    },
    stickyHeaderContent: {
        height: 76,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingHorizontal: 18,
    },
    stickyTitle: { fontSize: 23, fontWeight: '800' },
    stickyRangeChip: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 5,
        paddingHorizontal: 10,
        paddingVertical: 7,
        borderRadius: 12,
    },
    stickyRangeText: { fontSize: 12, fontWeight: '600' },
    loadingContainer: { flex: 1, justifyContent: 'center', alignItems: 'center' },
    pageHeader: { minHeight: 57, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: 13 },
    pageEyebrow: { fontSize: 10, fontWeight: '600' },
    pageTitle: { marginTop: 3, fontSize: 22, fontWeight: '800' },
    headerCard: { padding: 19, borderRadius: 24, marginBottom: 14 },
    totalLabel: { fontSize: 11, fontWeight: '600' },
    totalValue: { marginTop: 8, fontSize: 27, fontWeight: '800' },
    totalSubtitle: { marginTop: 5, fontSize: 10 },
    card: { borderRadius: 20, padding: 15, marginBottom: 12, borderWidth: 1 },
    cardTitle: { fontSize: 13, fontWeight: '800', marginBottom: 13 },
    chartContainer: { alignItems: 'center', marginBottom: 9 },
    pieCenterWrap: { alignItems: 'center' },
    pieCenterValue: { fontSize: 14, fontWeight: '800' },
    pieCenterLabel: { fontSize: 9, marginTop: 2 },
    legendContainer: { gap: 8 },
    legendItem: { flexDirection: 'row', alignItems: 'center', gap: 8 },
    legendDot: { width: 8, height: 8, borderRadius: 4 },
    legendText: { flex: 1, fontSize: 11, fontWeight: '500' },
    legendPercent: { fontSize: 11, fontWeight: '700' },
    pieTooltip: { paddingHorizontal: 10, paddingVertical: 5, borderRadius: 8 },
    pieTooltipText: { fontSize: 10, fontWeight: '600' },
    filterRow: { gap: 7, paddingBottom: 8 },
    filterChip: { paddingHorizontal: 13, paddingVertical: 7, borderRadius: 15, borderWidth: 1 },
    filterChipText: { fontSize: 10, fontWeight: '600' },
    trendHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: 12 },
    trendTitle: { marginBottom: 0 },
    trendChangeRow: { flexDirection: 'row', alignItems: 'center', gap: 6 },
    trendChangeLabel: { fontSize: 9 },
    trendChangeValue: { fontSize: 11, fontWeight: '700' },
    noDataText: { fontSize: 11, textAlign: 'center', paddingVertical: 18, lineHeight: 17 },
    tableHeader: { flexDirection: 'row', paddingVertical: 9, borderBottomWidth: 1 },
    tableHeaderCell: { fontSize: 9, fontWeight: '700' },
    tableRow: { flexDirection: 'row', paddingVertical: 10, borderBottomWidth: 1 },
    tableCell: { fontSize: 10 },
    colPlatform: { flex: 2.2 },
    colValue: { flex: 2.3, textAlign: 'right' },
    colConverted: { flex: 2.2, textAlign: 'right' },
    colPercent: { flex: 1.1, textAlign: 'right', fontWeight: '700' },
    colChange: { flex: 1.4, textAlign: 'right', fontWeight: '700' },
});
