import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
    screen: { flex: 1 },
    scrollView: { flex: 1 },
    content: { paddingHorizontal: 16 },
    ambientBlue: {
        position: 'absolute',
        top: 0,
        left: 0,
        width: 180,
        height: 180,
        borderRadius: 90,
        opacity: 0.62,
    },
    ambientPurple: {
        position: 'absolute',
        top: 160,
        right: 0,
        width: 150,
        height: 150,
        borderRadius: 75,
        opacity: 0.58,
    },
    summaryCard: {
        minHeight: 236,
        borderRadius: 30,
        borderWidth: 1,
        paddingHorizontal: 20,
        paddingVertical: 12,
        shadowOffset: { width: 0, height: 10 },
        shadowOpacity: 0.14,
        shadowRadius: 24,
        elevation: 5,
    },
    summaryHeader: {
        minHeight: 40,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
    },
    summaryTitle: { minWidth: 88, flexShrink: 0, fontSize: 17, fontWeight: '700' },
    headerActions: { flexDirection: 'row', alignItems: 'center', gap: 4 },
    headerButton: {
        width: 40,
        height: 40,
        alignItems: 'center',
        justifyContent: 'center',
        borderRadius: 20,
    },
    totalLabel: { marginTop: 4, fontSize: 12, lineHeight: 15 },
    totalValue: {
        minHeight: 40,
        marginTop: 1,
        fontSize: 34,
        lineHeight: 40,
        fontWeight: '800',
        letterSpacing: 0.1,
    },
    summaryFooter: {
        minHeight: 22,
        marginTop: 4,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
    },
    changeBlock: { flex: 1, minWidth: 0, flexDirection: 'row', alignItems: 'center', gap: 6 },
    changeBadge: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 3,
        paddingHorizontal: 7,
        paddingVertical: 4,
        borderRadius: 10,
    },
    changeValue: { fontSize: 11, fontWeight: '700' },
    changeCaption: { flexShrink: 1, fontSize: 11 },
    updatedText: { maxWidth: '42%', marginLeft: 8, fontSize: 10, textAlign: 'right' },
    summaryDivider: { height: 1, marginTop: 8 },
    summaryStats: { flexDirection: 'row', gap: 10, marginTop: 8 },
    summaryStat: {
        flex: 1,
        minHeight: 56,
        justifyContent: 'center',
        borderRadius: 16,
        paddingHorizontal: 12,
        paddingVertical: 8,
    },
    statLabel: { fontSize: 11 },
    statValue: { marginTop: 3, fontSize: 15, lineHeight: 18, fontWeight: '700' },
    attributionRow: { alignItems: 'flex-end', marginTop: 3 },
    stickyOverlay: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        zIndex: 20,
    },
    stickyHeader: {
        borderBottomWidth: 1,
        borderBottomLeftRadius: 22,
        borderBottomRightRadius: 22,
        shadowOffset: { width: 0, height: 8 },
        shadowOpacity: 0.14,
        shadowRadius: 18,
        elevation: 12,
    },
    stickyHeaderContent: {
        height: 84,
        justifyContent: 'space-between',
        paddingHorizontal: 18,
        paddingVertical: 10,
    },
    stickyGreetingRow: {
        height: 28,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
    },
    stickyTitle: { fontSize: 17, fontWeight: '700' },
    stickyBalanceRow: {
        height: 28,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
    },
    stickyBalanceLabel: { fontSize: 11, fontWeight: '600' },
    stickyBalanceValue: { maxWidth: '74%', fontSize: 21, fontWeight: '800', textAlign: 'right' },
    sectionHeader: {
        minHeight: 34,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        marginTop: 10,
        marginBottom: 10,
        paddingHorizontal: 3,
    },
    sectionTitle: { fontSize: 19, lineHeight: 24, fontWeight: '700' },
    sectionCount: { fontSize: 12 },
    assetList: { gap: 10 },
    emptyCard: { alignItems: 'center', padding: 24, borderRadius: 22, borderWidth: 1 },
    emptyIcon: { width: 48, height: 48, borderRadius: 16, alignItems: 'center', justifyContent: 'center' },
    emptyTitle: { marginTop: 12, fontSize: 14, fontWeight: '700' },
    emptyText: { marginTop: 6, textAlign: 'center', fontSize: 12, lineHeight: 18 },
});
